register:
    pattern:  /register
    defaults:
        _controller: UserBundle:Register:register

login:
    pattern:  /login
    defaults:
      _controller: UserBundle:Login:login

logout:
    pattern:  /logout

user:
    resource: "@UserBundle/Resources/config/routing.xml"
    prefix:   /user/

homepage:
    resource: "@HomepageBundle/Resources/config/routing.xml"
    prefix:   /

photo:
    resource: "@PhotoBundle/Resources/config/routing.xml"
    prefix:   /photo/