user:
    resource: "@UserBundle/Resources/config/routing.xml"
    prefix:   /

homepage:
    resource: "@HomepageBundle/Resources/config/routing.xml"
    prefix:   /

photo:
    resource: "@PhotoBundle/Resources/config/routing.xml"
    prefix:   /photo/

register:
    pattern:  /register
    defaults:
        _controller: UserBundle:Register:register

login:
    pattern:  /login
    requirements:
        _method:  POST

logout:
    pattern:  /logout