jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        wiosloCMS\UserBundle\Model\User: sha512

    providers:
        user:
            propel:
                class: wiosloCMS\UserBundle\Model\User
                property: Username

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            anonymous: true

            switch_user: { role: ROLE_SUPER_ADMIN, parameter: _sadfiug3487rg_w8d8ew67t }
            form_login:
                check_path: /login
                login_path: /login
                failure_path: /?login_error
            remember_me:
                key: "%secret%"
                lifetime: 31536000
                path: /
                domain: ~
            logout:
                path:   /logout
                target: /